name: natave_flutter
description: "NATAVE - Financial Organizer"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  fl_chart: ^1.2.0
  url_launcher: ^6.3.2
  flutter_secure_storage: ^10.0.0
  pdf: ^3.12.0
  printing: ^5.14.3
  sqflite: ^2.4.1
  path: ^1.9.1
  workmanager: ^0.9.0+3
  local_auth: ^2.3.0
  get_it: ^7.6.0
  provider: ^6.1.0
  logger: ^2.1.0
  connectivity_plus: ^6.1.1
  shimmer: ^3.0.0
  uuid: ^4.3.3
  shared_preferences: ^2.5.5
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/app_icon.jpg"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/config.json
    - assets/branding/
    - assets/fonts/
  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
        - asset: assets/fonts/Arial-Bold.ttf
          weight: 700
